### ISSUE TITLE
Incorrect area

### ISSUE THREAD

**Issue by sjb1604** [Richard-Hemingway/clubfinder#1]
Forfar & District, Steeple and Tayside Airgun clubs is not in Highlands and Islands... please amend to Angus - The NSRA were told to change this in the club finder. You could also add Arbroath Smallbore Rifle club in Angus too...

**Comment by Richard-Hemingway** [comment]
Thanks, the first three have been fixed now. Does ASRC have a website? I can only see the one for the "Arbroath Area FB Gun Club" (which also needs adding!)

**Comment by sjb1604** [comment]
Arbroath has no web presence.... I think the contact was through the secretary's private email and phone number. When they were on the clubfinder it was contact through the NSRA. You could also add Dundee Rifle and Pistol club (https://www.facebook.com/pages/category/Sports-Team/Dundee-Rifle-and-Pistol-183903899081635/) in Angus.

**Comment by Richard-Hemingway** [comment]
Thanks, added Dundee and also scraped the NRA clubs for Wales, Scotland & NI.
